### ISSUE TITLE
As a traffic analyst, I would like to properly manage some new Bluetooth installations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#124]
- [x] Activate again "galvani" and "caugusta" (inserted in the metadata list, should work automatically?"
- [x] Delete wrong station "Druso_Firenze"
- [x] Update metadata spreadsheet with new Bluetooth installations

**Comment by bertolla** [comment]
Bluetoothstations can not activate automatically because they are not pushed as whole but each single station syncs itself and we do  not have any business logic which handles that. Could be improved, but how would you handle that. Is a station to set inactive when it does not receive data for a certain amount of time???

**Comment by rcavaliere** [comment]
I think that in this case we know when they have to considered active and not active, I would not implement any automatic logic here. Like in this case we have to adjust the status of two stations that are reactivated. This is because this is the only cases in which we directly control the installation / removal of Bluetooth stations

**Comment by rcavaliere** [comment]
Wonderful! We have now plenty of new Bluetooth boxes thanks to CISMA (have a look at the map visualization on analytics...). Can you just check why the box "MasoPieve" is not displayed on the map? Otherwise everything works perfectly!

**Comment by bertolla** [comment]
This is easy. In the spreadsheet the station was called Maso Pieve instead of Maso_Pieve and the coordinates where therefore not set. I changed it now and it should work shortly
