### ISSUE TITLE
As an Open Data hub project manager I want the Quota (limit per number of requests) active on the Open Data Hub API in order to activate the "Quota" paid service.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-core#241]
Priority: high
Deadline: 15 April 2022

**Comment by RudiThoeni** [comment]
done a Test implementation from scratch (without a library)
https://github.com/RudiThoeni/WebApiWithQuotas

where:
-Response Message can be defined
-i implemented 3 types, anonymous / with referer / logged user
-Rate limit is added in form of Requests / sec
-Rate Limit Headers added (found some standard)

will show it in the next meeting, if ok i add this to the tourism api.......

**Comment by Piiit** [comment]
@noi-techpark/ttdigital Quota for mobility is online, please test on https://mobility.api.opendatahub.testingmachine.eu ... You need to look at the response headers to see which quota policy has been chosen and how many calls are left or how long it takes to recover from used up limits... I have set 20 requests per second for GUEST accounts without referer, this means cached by IP + URL path... not easy to hit that limit manually. For a referer the limit is 100 r/s and for logged-in users 200 r/s... I kept the 100MB reponse size for everyone and the 30 second timeout also, to be sure that nobody kills the server... however, those limits exist now since a year and I did not see any issue with them until now.

**Comment by RudiThoeni** [comment]
New policy now is:
https://tourism.opendatahub.bz.it/Test/TestQuotasettings

- Anonymous
- Referer (If referer is added on each request)
- Basic (Logged User with no Role in Keycloak assigned)
- Advanced (Logged User with Role "Advanced" in Keycloak assigned
- Premium (Logged User with Role "Premium" in Keycloak assigned

**Comment by Piiit** [comment]
+ Admin (no restrictions at all)

**Comment by Piiit** [comment]
New policies explained here --> https://github.com/noi-techpark/odh-docs/wiki/Api-Quota

This is also the document linked as hint to the JSON error response of each API

**Comment by Piiit** [comment]
Mobility API done, documentation updated and last security issues tested and solved. Ready for production...

**Comment by RudiThoeni** [comment]
after going online we have to monitor the HTTP Status 429

**Comment by ohnewein** [comment]
We will activate Quota after the Open Data Hub Day.
