### ISSUE TITLE
Bluetooth Elaboration Chain disappeared???

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#256]
It seems that we don't see any Bluetooth / LinkStation elaboration anymore? See screenshot down. I also don't see the elaboration component on https://github.com/noi-techpark/bdp-elaborations. Did you touch something?

![Screenshot from 2022-06-27 22-48-58](https://user-images.githubusercontent.com/9825179/176033346-b5c5d5cd-1902-47af-962a-c320335e1242.png)

**Comment by dulvui** [comment]
@rcavaliere I think that the Bluetooth elaboration has it own repo:
https://github.com/noi-techpark/BluetoothTrafficElaboration
I changed the CI 6 months ago, the rest should be the same. I'll investigate now whats wrong.
Should I move it to the elaborations repo and archive this repo?

**Comment by rcavaliere** [comment]
@dulvui yes please! This should be the reference source code for all these computations

**Comment by dulvui** [comment]
The LinkStations don't have a provenance in the database and so with the some of the latest changes on the Ninja API they were not visible anymore, because measurements with no provenance where not returned.
Now the Ninja API returns again also measurements with no provenance, so the LinkStations are visible again.

We have to fix this "no provenance" issue in future and add a provenance to the LinkStations measurements and measurementshistory and create a provenance not null constraint on database level, so that future measurements must have an provenance.

**Comment by dulvui** [comment]
Yes, I will try to find out which data-collector or elaboration creates this LinkStations with no provenance and add it there. After that I'll adapt also the history.
