### ISSUE TITLE
The webmaster wants to be able to integrate web-stats data into the website, to fulfill transparency obligations.

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/bdp-core#268]
We have a request to provide real-time information about web-stats as a widget.

Should this be provided through the Open Data Hub?

1. MATOMO becomes a Data Provider to the Open Data Hub.
1. A web component can visualize data from the Open Data Hub, and the user of the web component can configure the query to set the MATOMO data.

Would this be easily possible or would it be better to have a widget which accesses directly MATOMO. Maybe MATOMO provides such widgets already?

Therefore I see 3 possible scenarios:

1. Provide a web component to NOI, which visualizes data about the NOI website provided through the Open Data Hub.
1. Provide a web component to NOI, which consumes the MATOMO API directly.
1. Provide a MATOMO widget, which consumes the MATOMO API directly, if this widget exists.

Can you provide me an evaluation about these 3 options?

**Comment by dulvui** [comment]
@ohnewein I checked now and Matomo already has widgets that show the requested data. The problem is, that you can see the data only if you are logged in and it would be possible to show it to everyone, but only by opening all data of matomo to anonymous users.
So scenario 2 and 3 would only work, if it is okay that all data is public visible.
Matomo says that in that case, it still hides Personally Identifiable Information like Visitor Profile and IP addresses to the public:
https://matomo.org/faq/how-to/faq_20130/

But I would anyway suggest scenario 1:
Matomo has also an easy API, so writing the data into the Open Data Hub and then showing it in a webcomponent would be quite easy and so we can also style it how we want and only show data we actually want to share with everyone.
I would estimate the effort for one of our Software architects to minimum 1 and maximal 2 working days or about one week for our customer care.

**Comment by ohnewein** [comment]
Thank you. I have sent an offer based on your evaluation to the requester.

**Comment by dulvui** [comment]
@ohnewein I checked now the Matomo API and it is quite easy to get the data we need. I was already able to create the URL to fetch the data of our custom report from Matomo.

Now the next steps are:
 - [ ] create data collector that writes the data to the Open Data Hub
 - [ ] create web component showing the data from the Open Data Hub

I'm pretty confident that I can can create both until next Friday 21.04.2023. If not I will let you know before that date, so we still have a week time to decide on how to do it in a static way.

**Comment by ohnewein** [comment]
@dulvui thank you for you evaluation. I will communicate this timeline to our legal and communication units.

**Comment by dulvui** [comment]
@ohnewein The first version of the webcomponent showing the visits of the websites is available on testing
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/noi-stats

This is showing the daily visits of the pages, but I think the yearly visits are needed.
I will extend the data collection on the Open Data hub to get also the monthly and yearly data and show it in the webcomponent. The webcomponent will have a configuration, where daily/montly/yearly options can be chosen.

**Comment by ohnewein** [comment]
Hi @dulvui , looks very promising!

**Comment by dulvui** [comment]
@clezag extended now the data collector and the webcomponent shows now  the daily, weekly, monthly and yearly visits.
The text, fontsize and which websites data is shown, can be configured too.
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/noi-stats

Should we send this webcomponent to the legal and communication units, to get some feedback?
