### ISSUE TITLE
As an implementer of AI-as-a-Service tool that provides as outputs "forecasts", I would like to have the possibility to overwrite forecasts records that were previously computed, and which are updated through a new run of the forecasting tool

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#285]
Functionality requested for forecasting models that provide as output forecasts for a certain interval. These intervals overlap at different runs. Example
- forecast run 1 - forecast for the time period 6 AM  - 6 PM
- forecast run 2 - forecast for the time period 7 AM  - 7 PM
The output of forecast run 2 should overwrite the one computed by the forecast run 1. At the end for a specific timestamp we just provide the forecast of the "last" run with interval that covers this timestamp.

@clezag @dulvui  can you start look at this request in the next sprint? We will need this for the next elaboration by CISMA and u-hopper

**Comment by clezag** [comment]
@rcavaliere What is the status of this issue? Are they blocked and waiting for us, or can we wait with this implementation until we have the concrete use case?

**Comment by rcavaliere** [comment]
@clezag CISMA and u-hopper are working on this, so should already be prepared for this!

**Comment by clezag** [comment]
@rcavaliere I think the use case you described should work already. The prediction at 6AM would have "6AM" as timestamp, the prediction at 7AM would have 
"7 AM", so the second one is "later" in terms of what the API looks at for allowing the write. 
The API doesn't know or care that they overlap in time frame, as the fact that it's a 12h prediction will be expressed as period or datatype, which the API doesn't look at when considering what's newer.

The reason why I'm apprehensive about doing some kind of delete/update feature on historical data is not that it would be difficult to implement (I think it will be relatively easy), but that once this becomes commonplace, it will have a bad impact and limits on performance optimizations and future things we can do with the API/Database. I think it would be good to keep time series data as close to immutable (or "add only") as possible.

@dulvui since you have followed the technical side of these issues, Is there a part we currently cannot handle?
I know you talked about edge cases where elaborations have to retroactively "fill in" holes in the past. If it's just that, maybe we can allow some kind of "write historical data, but don't check the timestamp and don't update latest measurement" flag. That would be much better in terms of time series integrity

**Comment by rcavaliere** [comment]
@clezag are you sure this will already work? I assume that if you have already a prediction in the future that has a certain timestamp, if there is a new updated forecast for this timestamp this wont' be stored since the value is already there. So, in my example above, only the forecast for the additional hour (i.e. 7 PM) would be stored. In this case we would need to overwrite the forecasts between 7 AM and 6 PM, and add the forecast for 7 PM (I am assuming forecasts with period = 1 hour)

**Comment by clezag** [comment]
I have seen other cases (e.g. [parking forecast](https://mobility.api.opendatahub.testingmachine.eu/v2/flat/ParkingStation/*/latest?select=tname,mperiod)) where this has been solved by having datatypes like "+2 hour prediction", "+3 hour prediction" and so on, or use the period to express how far into the future the prediction looks.

So you would have:
|timestamp|period|datatype|created_at|
|----------------|---------|--------------|---------------|
|8:00 | 7200 | + 2 hour prediction | 6:00 |
|8:00 | 3600 | + 1 hour prediction | 7:00 |

The advantage when using the period like this, is that a user can first get all the records for a given timestamp, and then sort by period to get the most recently updated, and thus most accurate one.  
But that could also be done by using the mtransactiontime field, or the (seldom used and not documented in swagger) metadata field of our datatypes, e.g. tmetadata.prediction_hours = 1

**Comment by rcavaliere** [comment]
@clezag yeah, you are perfectly right. We already support this, let's make like parking forecasts. We can already close this user story :-)
