### ISSUE TITLE
As a project manager, I would like that all bugs associated to the migration to bdp-core v2 are fixed

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#85]
Following issues have to be fixed:
- [x] Metadata information for parking BZ not displayed properly
- [x] Types associated to Bluetooth stations (elaborations) should be fixed (currently not visible on analytics)
- [x] Traffic data not visible on analytics: issue related to data provider?
- [x] Types associated to Link stations (in analytics: vehicular travel time) not visible -> elaborations should be visible

**Comment by rcavaliere** [comment]
Following issues have to be fixed:
- [] Metadata information for parking BZ not displayed properly

**Comment by bertolla** [comment]
@rcavaliere 
1. As I told you after the meeting for parking it's an issue, not because we lost data but that the workflow expects the datacollector to provide the meta-data and **not** that we manually add informations to the database like we did 2013. If the municipality wants to display the metadata of their parkinglots they need to provide it. The data we had, was inserted by us, never checked and never maintained and in the end it would have been up to us to take the blame for bad data quality . We don't even get the coordinates from their webservice :frowning_face: . With the data provided we can't even show the parking lots on a map. We can only make this work with the data and create manual mappings are just workaround which do not get maintained.
2. Will check this and in case discuss changes with Peter.
3. Wrote you an email about this. Can't fix this as long as we get firewalled.
4. Will check also this.

**Comment by Piiit** [comment]
@rcavaliere 
- Bluetooth and vehicular travel time should work now
- Parking Meta Data must be fixed by the external data source / provider.
- Also traffic seems to work: See this [permalink](https://analytics.mobility.bz.it/#%7B%22active_tab%22:0,%22height%22:%22400px%22,%22auto_refresh%22:false,%22scale%22:%7B%22from%22:1548889200000,%22to%22:1554588000000%7D,%22graphs%22:%5B%7B%22category%22:%22Traffic%22,%22station%22:%22municipalitybz:7l5d0%22,%22station_name%22:%22Stazione%20Traffico%20-%20Ponte%20Virgolo%20Lane%205%20Direction%200%22,%22data_type%22:%22average-vehicle-speed%22,%22unit%22:%22km/h%22,%22period%22:%22600%22,%22yaxis%22:1,%22color%22:3%7D%5D%7D)

... please test.
