### ISSUE TITLE
As a consumer of the ODH Mobility API, I want to get a descriptive error message, to debug wrong API usage faster

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#95]
- [x] Create a simple representation to encode an error, including a description, http codes and some hints to fix the wrong usage easily
- [x] Catch errors as soon as possible within where-clause parsing and give good hints how to solve issues
- [x] Catch SQL exceptions and do not expose them to the API consumer (security and ease-of-use)

**Comment by Piiit** [comment]
@RudiThoeni  @alexlanz  Please destroy my API...

https://tomcatsec.testingmachine.eu/reader2/

Just try to write wrong requests in where or select clauses or anywhere else. Please, break my API :-)

**Comment by alexlanz** [comment]
Not found message if trailing slash is missing:

- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy
- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/

**Comment by alexlanz** [comment]
Returned list is not very readable. Items could be sorted by name:

https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/

**Comment by alexlanz** [comment]
Response could contain meta information and not only data. For example the default offset and limit values are not provided in the response, but applied in the query/request. When adding these information in the request, errors and questions will be prevented from the users.

Example:

```json
{
	"offset": 0,
        "limit": 200,
	"data": {
		"ECharingStation": {
		}
	}
}
```

**Comment by alexlanz** [comment]
The prefix characters in the value names of a respons are a little bit irritating, when using the API for the first time. For me it seemed that "scode" was stored like this in the database only for the stations "EChargingStation". Maybe you could reevaluate this approach.

For me as a consumer of the API, I would prefer to no prefix the values so that I can read the labels better. But you also have the point of view as a developer of the API.

**Comment by alexlanz** [comment]
For the following two queries, there should be always the same number of results and only the returned fields different:

- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/BikesharingStation/*?select=scode,tname
- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/BikesharingStation/*?select=tname

**Comment by alexlanz** [comment]
Why is the station value a null value when no results are given for the following request: https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/BikesharingStation/*?select=tname

Shouldn't it be an empty object to prevent parsing problems for the users? ({})

**Comment by alexlanz** [comment]
Should the value "stations" in the response maybe an array instead of an object? What benefits do you see when providing the data as object? For me at first it was irritating to see an object when asking for a list of things. But also for me from as a consumer of the API it would not make much difference during development.

**Comment by alexlanz** [comment]
The value "mperiod" is not provided in the result when explicitly querying for it:

- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/BikesharingStation/*?select=scode
- https://tomcatsec.testingmachine.eu/reader2/api/v2/hierarchy/BikesharingStation/*?select=scode,mperiod

**Comment by Piiit** [comment]
@alexlanz  
Fixed most of your issues and opened two new issues to remember the missing two
